"""add system_prompts table and messages.system_prompt_id

Revision ID: 014d52c9da5e
Revises: afb81b1310b1
Create Date: 2026-06-07 10:51:31.046469

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014d52c9da5e"
down_revision: str | Sequence[str] | None = "afb81b1310b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_prompts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("messages", sa.Column("system_prompt_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "messages",
        "system_prompts",
        ["system_prompt_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "system_prompt_id")
    op.drop_table("system_prompts")
    # ### end Alembic commands ###
