"""add tool_name column to messages

Revision ID: 26f682471bc7
Revises: a76f7ff8cc06
Create Date: 2026-06-07 11:27:36.426726

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26f682471bc7"
down_revision: str | Sequence[str] | None = "a76f7ff8cc06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("tool_name", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "tool_name")
    # ### end Alembic commands ###
