"""add tool call columns to messages

Revision ID: faa04ba69d75
Revises: c91d4e7a6b2a
Create Date: 2026-06-21 12:51:46.530634

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faa04ba69d75"
down_revision: str | Sequence[str] | None = "c91d4e7a6b2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("tool_call_id", sa.String(length=100), nullable=True))
    op.add_column("messages", sa.Column("tool_input", sa.JSON(), nullable=True))
    op.add_column("messages", sa.Column("tool_output", sa.JSON(), nullable=True))
    op.add_column("messages", sa.Column("output_preview", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "output_preview")
    op.drop_column("messages", "tool_output")
    op.drop_column("messages", "tool_input")
    op.drop_column("messages", "tool_call_id")
    # ### end Alembic commands ###
